-- AlterTable
ALTER TABLE "Blog" ADD COLUMN     "blogCreatedTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "userCreatedTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
